apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
  labels:
    app: simple-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: imraz25/flask_app1:v1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: app.py
        - name: FLASK_ENV
          value: production
