apiVersion: v1
kind: Service
metadata:
  name: simple-flask-service
spec:
  selector:
    app: simple-flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
